[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["node"]

[build.nixpacksPlan.install]
cmds = ["npm ci", "cd backend && npm install", "cd backend && npx prisma generate"]

[build.nixpacksPlan.build]
cmds = ["cd backend && tsc"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"

# Database will be automatically provided by Railway PostgreSQL service
# Required environment variables to set in Railway:
# - JWT_SECRET (generate a secure random string)
# - FRONTEND_URL (URL of your deployed frontend)