# Railway configuration for Go backend
# The Go backend is in the go-backend/ directory

[build]
builder = "dockerfile"
dockerfilePath = "go-backend/Dockerfile"
watchPatterns = ["go-backend/**"]

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Railway environment variables required (set in Railway dashboard):
# - DATABASE_URL (auto-populated by PostgreSQL addon)
# - JWT_SECRET (generate with: openssl rand -base64 32)
# - FRONTEND_URL (e.g., https://community-centres-platform.vercel.app)
# - PORT (optional, Railway auto-assigns if not set)
# - GIN_MODE=release (recommended for production)