version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ccp
      POSTGRES_PASSWORD: ccp
      POSTGRES_DB: ccp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccp"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://ccp:ccp@db:5432/ccp?sslmode=disable
      JWT_SECRET: ${JWT_SECRET:-RYmSUSFFOIPU+v/GndHvyxQpltIyf2SfG+M8uh+Rumc=}
      JWT_EXPIRES_IN: 7d
      PORT: 8080
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
