[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "never"

[[services]]
name = "kampala-centers-api"

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[services.variables]
NODE_ENV = "production"
PORT = "3001"

# Database will be automatically provided by Railway PostgreSQL service
# JWT_SECRET should be set in Railway environment variables
# FRONTEND_URL should be set to your deployed frontend URL